### ISSUE TITLE
API improvements

### ISSUE THREAD

**Issue by RivenSkaye** [Irrational-Encoding-Wizardry/vs-masktools#7]
None of the edge detection classes seem to be taking any arguments for constructors or `__init__` calls, so the current need to instantiate all of them in a script becomes somewhat unwieldy and doesn't serve much purpose.
I have two suggestions that could improve the user friendliness of the API in this regard, but perhaps there are other solutions as well.

1. Provide a (sub)module of instantiated objects for importing. This would allow `from vsmask import fdog` and `fdog.edgedetect(*args)`, has the benefit of not requiring users to instantiate everything. Might come with more initialization overhead that hits star and direct parent imports rather hard, but `__pycache__` should lessen that hit considerably. Vardë's old debanding code provided a similar API, which was nice to work with.
2. Provide the methods intended to be part of the public API as `@staticmethod`s. This would allow `vsmask.edge.FDoG.edgedetect(*args)`. As a staticmethod, this wouldn't break the current API, as the implicit `self` argument is never passed. This might require some more code and checks in inheriting classes though, possibly in the form of wrapping the call to `super`.

There is also the option of making them classmethods, but this would be a backwards-incompatible change as _all_ instances of implicit `self` become an implicit `cls`. Breaking backwards compatibility can be mitigated by performing checks on the first argument that allows for dynamically choosing the behavior, but this brings extra runtime overhead to _every_ call made and would most probably result in every `cls` instance having to be instantiated and called again, doubling the overhead on this API.

I'm personally most partial to suggestion 1, with the pre-instantiated objects being made available either as top-level importable name (`from vsmask import fdog`), or as part of a single submodule (`vsmask.masks.FDoG`)

**Comment by Setsugennoao** [comment]
I already solved everything by decorating edgedetect and ridgedetect with inject_self, so you can just do FDoG.edgemask
In the constructor you can pass kwargs.

**Comment by Setsugennoao** [comment]
Vardë's old debanding wrappers were deprecated and remived by the same functionality.
Before: 
F3kdb().deband and dumb3kdb
Now:
F3kdb.deband, F3kdb(**kwargs) just for when being used as higher order function.
